### ISSUE TITLE
Оверхедный memset

### ISSUE THREAD

**Issue by alexmikhalevich** [Twodragon/linux_2018#4]
С какой целью ты каждый раз обнуляешь память, в которую сейчас собираешься писать? Например, тут: https://github.com/Twodragon/linux_2018/blob/fe8137a390a0743baa4844d9117faeecb61160c0/hw4/FS_Server/Network_utils.c#L20

**Comment by sefimochkin** [comment]
У меня просто валгринд ругался, что пишу в неинициализированную память, и я
решил занулить уж все на всякий случай)

С уважением,
Ефимочкин Сергей, студент 597 группы

пт, 11 мая 2018 г., 20:40 Alexander Mikhalevich <notifications@github.com>:

**Comment by alexmikhalevich** [comment]
Но в итоге ты платишь за то, что тебе не нужно...
