### ISSUE TITLE
Уязвимость

### ISSUE THREAD

**Issue by alexmikhalevich** [Twodragon/linux_2018#5]
Могу отправить твоему серверу шеллкод и заставить его выполниться. Критическая уязвимость, необходимо пофиксить. Также, проанализируй остальной свой код на наличие аналогичных проблем. https://github.com/Twodragon/linux_2018/blob/fe8137a390a0743baa4844d9117faeecb61160c0/hw4/FS_Server/Server.c#L55

**Comment by sefimochkin** [comment]
Не понимаю, почему он выполнится? уязвимость в sscanf-e?

**Comment by alexmikhalevich** [comment]
так у тебя ж переполнение

**Comment by sefimochkin** [comment]
А, из-за пробелов в "%s %s %s"?

**Comment by alexmikhalevich** [comment]
можно и так сказать  
я имею ввиду, что, например, первому ```%s``` может соответствовать строка длиннее 32х символов

**Comment by sefimochkin** [comment]
А, понял, точно. Окей, поправлю

**Comment by sefimochkin** [comment]
Привет!
Поправил всё, о чем ты говорил.
https://github.com/Twodragon/linux_2018/tree/master/hw4 <https://github.com/Twodragon/linux_2018/tree/master/hw4>

С уважением,
Ефимочкин Сергей, студент 597 группы

**Comment by alexmikhalevich** [comment]
ок
просто вопрос: а в чем идея была менять порт на 8888 и потом обратно?)

**Comment by sefimochkin** [comment]
Я, пока отлаживал и чинил, поломал много сокетов, которые были привязаны к портам, а потом уж для красоты обратно поменял)

С уважением,
Ефимочкин Сергей, студент 597 группы

> 14 мая 2018 г., в 23:17, Alexander Mikhalevich <notifications@github.com> написал(а):
> 
> просто вопрос: а в чем идея была менять порт на 8888 и потом обратно?)
> 
>
